image:
  file: .gitpod.Dockerfile
tasks:
  - name: Build
    init: cmake -B build && cmake --build build # Example build command
    command: ./build/your-executable # Example run command
ports:
  - port: 8080 # Example port if your application uses one
    onOpen: open-browser # Automatically opens the port in a new browser tab
