image:
  file: .gitpod.Dockerfile

tasks:
  - init: sudo pacman -Syu --noconfirm
    command: echo "Arch Linux workspace is ready!"

ports:
  - port: 8000
    onOpen: open-preview

vscode:
  extensions:
    - ms-vscode.cpptools
    - ms-python.python
    - esbenp.prettier-vscode
